services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: unless-stopped
    volumes:
      - ./data/storage:/var/www/html/storage
      - .env:/var/www/html/.env
    networks:
      - colocs
    ports:
      - "8080:80"
    env_file:
      - .env
    environment:
      - PHP_MEMORY_LIMIT=512M
      - PHP_MAX_CHILDREN=100
    depends_on:
      mysql:
        condition: service_healthy

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: ${DB_PORT:-3306}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-secret}
      UPLOAD_LIMIT: 10M
    #ports:
    #  - "5050:80"
    networks:
      - colocs
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_DATABASE: ${DB_DATABASE:-app}
      MYSQL_USER: ${DB_USERNAME:-laravel}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
    #ports:
    #  - "${DB_PORT:-3306}:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - colocs
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD:-secret}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  colocs: